# Generated by Django 2.1.3 on 2018-12-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('mediapleer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сities',
            new_name='City',
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediapleer.City'),
        ),
    ]
