# Generated by Django 2.1.3 on 2018-12-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapleer', '0003_auto_20181203_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='concerts',
            field=models.ManyToManyField(null=True, to='mediapleer.Concert'),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(null=True, to='mediapleer.Genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='feat',
            field=models.ManyToManyField(null=True, to='mediapleer.Band'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bands',
            field=models.ManyToManyField(null=True, to='mediapleer.Band'),
        ),
        migrations.AlterField(
            model_name='user',
            name='concerts',
            field=models.ManyToManyField(null=True, to='mediapleer.Concert'),
        ),
    ]
