# Generated by Django 2.1.3 on 2018-12-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapleer', '0006_auto_20181211_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('bands', models.ManyToManyField(blank=True, to='mediapleer.Band')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediapleer.City')),
                ('concerts', models.ManyToManyField(blank=True, to='mediapleer.Concert')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='concerts',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
