# Generated by Django 2.1.3 on 2018-12-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapleer', '0009_auto_20181215_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='per',
        ),
    ]
