# Generated by Django 2.1.3 on 2018-12-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapleer', '0010_auto_20181215_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'permissions': (('can_change', 'Delete or add albums'),)},
        ),
    ]
